# GPU-Focused Runner Configuration Template
# Optimized for CUDA workloads, ML training, and GPU-intensive tasks

runner:
  name: "gpu-runner"
  labels:
    - self-hosted
    - windows
    - X64
    - gpu
    - cuda
    - ml
  group: "GPU"

paths:
  runner_home: "C:\\actions-runner"
  work_directory: "C:\\actions-runner\\_work"
  temp_directory: "C:\\Temp"
  log_directory: "C:\\actions-runner\\logs"

resources:
  max_concurrent_jobs: 1  # Run one GPU-intensive job at a time
  cpu:
    max_cores: 0
    affinity: ""
  memory:
    max_memory_gb: 32
    reserved_memory_gb: 8
  disk:
    min_free_space_gb: 200  # More space for ML datasets
    auto_cleanup: true
    cleanup_per_job: true

timeouts:
  job_timeout_minutes: 720  # 12 hours for long training jobs
  queue_timeout_minutes: 30
  step_timeout_minutes: 360

environment:
  system:
    CUDA_PATH: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.0"
    CUDNN_PATH: "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.0"
    DOTNET_ROOT: "C:\\Program Files\\dotnet"
    PYTHON_VERSION: "3.11"
  custom:
    TF_FORCE_GPU_ALLOW_GROWTH: "true"
    PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"

gpu:
  enabled: true
  cuda_version: "12.0"
  vram:
    reserved_vram_gb: 4
    max_vram_gb: 0
  compute_mode: "exclusive"

unity:
  enabled: false

docker:
  enabled: true
  isolation_mode: "process"
  container_limits:
    memory_gb: 16
    cpu_cores: 8
  auto_cleanup_containers: true
  auto_cleanup_images: false

monitoring:
  enabled: true
  health_check_interval: 180
  alerts:
    runner_offline: true
    low_disk_space: true
    high_cpu_usage: true
    high_memory_usage: true
    job_failure: true
  thresholds:
    cpu_warning_percent: 85
    cpu_critical_percent: 98
    memory_warning_percent: 90
    memory_critical_percent: 98
    disk_warning_gb: 200
    disk_critical_gb: 150

security:
  firewall_enabled: true
  block_external_access: false
  audit_logging: true

logging:
  level: "info"
  retention_days: 14
  max_file_size_mb: 100
  rotation_enabled: true

maintenance:
  auto_update: false
  maintenance_window: "0 3 * * 0"
